### ISSUE TITLE
Doesn't seem to work for CR3 

### ISSUE THREAD

**Issue by han-k59** [laheller/FPLibRaw#1]
Thanks for this very useful code.  I intend to use it for my application. 

It works for CR2 files but it doesn't work for me for CR3 files. It  seems to works but no files are produced. The original LibRaw program unprocessed_raw.exe works with the same CR3 files.

I download the CR3 raw files form
https://drive.google.com/drive/folders/1-ZoYTZlIOqkNJSXUrGPES_OWEBinD_cq 

Han

**Comment by laheller** [comment]
> Thanks for this very useful code.  I intend to use it for my application. 
> 
> It works for CR2 files but it doesn't work for me for CR3 files. It  seems to works but no files are produced. The original LibRaw program unprocessed_raw.exe works with the same CR3 files.
> 
> I download the CR3 raw files form
> https://drive.google.com/drive/folders/1-ZoYTZlIOqkNJSXUrGPES_OWEBinD_cq 
> 
> Han

Hi!

Thanks for feedback, I'll check with the provided CR3.

BR,

Ladislav

**Comment by laheller** [comment]
@han-k59 

The below sample works for me perfectly. It creates TIFF from CR3.

```
program TestApp;
uses Crt, LibRaw;

const
  InFile : PChar = 'C:\Users\Ladislav\Downloads\273A6915.CR3';
  OutFile : PChar = 'C:\Users\Ladislav\Downloads\273A6915.tiff';

var
  handler: Pointer;
  err: LibRaw_errors;

BEGIN
  WriteLn('Testing CR3...');
  handler := libraw_init(LibRaw_init_flags.LIBRAW_OPTIONS_NONE);
  libraw_set_output_tif(handler, LibRaw_output_formats.TIFF);
  libraw_set_no_auto_bright(handler, 0);

  WriteLn('Opening CR3...');
  err := libraw_open_file(handler, InFile);
  if (err <> LibRaw_errors.LIBRAW_SUCCESS) then begin
    WriteLn('Open:            ' + libraw_strerror(err));
    libraw_close(handler);
    Write('Press any key...');
    ReadKey;
    Exit;
  end;

  WriteLn('Unpacking CR3...');
  err := libraw_unpack(handler);

  WriteLn('Processing CR3...');
  libraw_dcraw_process(handler);

  WriteLn('Writing to TIFF...');
  libraw_dcraw_ppm_tiff_writer(handler, OutFile);

  WriteLn('Closing CR3...');
  libraw_close(handler);

  Write('Press any key...');
  ReadKey;
END.


```

**Comment by han-k59** [comment]
Your new example works but the original demo program destroys the CR3 and now also CR2 files. At the end of processing the input file is overwritten to a small file. No other files are created.

I do the following:

demo.exe 273A9512.CR3
or 
demo.exe D:\temp\FPLibRaw-master\FPLibRaw-master\273A9512.CR3

same result in both cases. The filesize reduces to from 49851 to 4574 kbytes as soon it is in the last phase converting to RGB

**Comment by han-k59** [comment]
The .CR3 file size first doubles to about 88000 kbytes before it reduces 5018 kbytes. Something goes wrong with the file names.

**Comment by han-k59** [comment]
There two problem with the demo program:

err := libraw_dcraw_ppm_tiff_writer(handler, PChar(ReplaceStr(PChar(ParamStr(1)),'.cr2','.tiff')));
 
1) cr2 is specified. This will never work for cr3
2) ReplaceStr. This is a case sensitive. It wil not work for CR2.
and applying Replacestr on a pchar? 

Better to use =ChangeFileExt(ParamStr(1),'.tiff') 


Same for these two
  bmp.SaveToFile(ReplaceStr(PChar(ParamStr(1)),'.cr2','.bmp'));
  err := libraw_dcraw_thumb_writer(handler, PChar(ReplaceStr(PChar(ParamStr(1)),'.cr2','.jpg')));

**Comment by laheller** [comment]
Thanks for findings, obviously the hardcoded stuff is the problem. I'll fix the demo.

**Comment by laheller** [comment]
@han-k59 
Issues fixed, now the demo should work properly.
