### ISSUE TITLE
Sample for creating unprocessed 16 bit PGM files.

### ISSUE THREAD

**Issue by han-k59** [laheller/FPLibRaw#2]
Would it be possible to add sample code to create 16 bit PGM files like "unprocessed_raw"?

**Comment by han-k59** [comment]
My intention is to write the raw files a FITS files including some important metadata information for astronomy like exposure time and sensor temperature.  I also intend to ignore the so called masked pixels if possible. The current LibRaw unprocessed_raw includes the masked pixel areas which can confuse the stacking process of my program (ASTAP). DCRaw doesn't show that behavior. Your code will hopefully also allow to write directly FITS files instead of first saving them as PGM/TIFF files. This if direct access to the memory containing the pixels is possible.

**Comment by laheller** [comment]
> My intention is to write the raw files a FITS files including some important metadata information for astronomy like exposure time and sensor temperature.  I also intend to ignore the so called masked pixels if possible. The current LibRaw unprocessed_raw includes the masked pixel areas which can confuse the stacking process of my program (ASTAP). DCRaw doesn't show that behavior. Your code will hopefully also allow to write directly FITS files instead of first saving them as PGM/TIFF files. This if direct access to the memory containing the pixels is possible.

Working on a wrapper for NASA's CFITSIO library.
It's a very big library, so the wrapper creation also will take a while...

**Comment by han-k59** [comment]
Writing FITS files is easy. You will not need such a big library. I have the FITS read/write routines in Pascal available.

**Comment by laheller** [comment]
> Writing FITS files is easy. You will not need such a big library. I have the FITS read/write routines in Pascal available.

Then I don't fully understand, what you need.

**Comment by han-k59** [comment]
I was looking for an example/demonstration code. 

Reading metadata is clear
Reading memory seem clear in your example demo.pas but bit size per pixel is unclear. Is it raw 16 bit or 8, 12 or  14 bit? Is it really raw or debayered?
Reading which pixels are masked is unclear. Maybe not possible.

I will work on it.

**Comment by laheller** [comment]
> Would it be possible to add sample code to create 16 bit PGM files like "unprocessed_raw"?

Here is, how to create 16bit per pixel PPM from the input CR3:

```
program TestApp;
uses Crt, LibRaw;

const
  InFile : PChar = 'C:\Users\Ladislav\Downloads\273A6915.CR3';
  OutFile : PChar = 'C:\Users\Ladislav\Downloads\273A6915.ppm';

var
  handler: Pointer;
  err: LibRaw_errors;

BEGIN
  WriteLn('Testing CR3...');
  handler := libraw_init(LibRaw_init_flags.LIBRAW_OPTIONS_NONE);
  libraw_set_output_tif(handler, LibRaw_output_formats.PPM);
  libraw_set_no_auto_bright(handler, 0);
  libraw_set_output_bps(handler, LibRaw_output_bps.BPS16);

  WriteLn('Opening CR3...');
  err := libraw_open_file(handler, InFile);
  if (err <> LibRaw_errors.LIBRAW_SUCCESS) then begin
    WriteLn('Open:            ' + libraw_strerror(err));
    libraw_close(handler);
    Write('Press any key...');
    ReadKey;
    Exit;
  end;

  WriteLn('Unpacking CR3...');
  err := libraw_unpack(handler);

  WriteLn('Processing CR3...');
  libraw_dcraw_process(handler);

  WriteLn('Writing to PPM...');
  libraw_dcraw_ppm_tiff_writer(handler, OutFile);

  WriteLn('Closing CR3...');
  libraw_close(handler);

  Write('Press any key...');
  ReadKey;
END.

```

**Comment by han-k59** [comment]
Thanks for the example. Yes 16 bit works However changing from TIFF to PPM doesn't change the color output. The output is still a color image. I have added this line:

libraw_set_output_color(handler, LibRaw_output_color.raw );

But it still stays in color. How to force in real raw?

Regards, Han

**Comment by laheller** [comment]
> Thanks for the example. Yes 16 bit works However changing from TIFF to PPM doesn't change the color output. The output is still a color image. I have added this line:
> 
> libraw_set_output_color(handler, LibRaw_output_color.raw );
> 
> But it still stays in color. How to force in real raw?
> 
> Regards, Han

@han-k59 
I am not 100% familiar with the original library and this FreePascal stuff is just a wrapper, means it calls the original libraw.dll, so to be honest I don't know.
You still can ask the author of original library at [Libraw forums](https://www.libraw.org/forum) for help.

BR,

Ladislav

**Comment by han-k59** [comment]
Okay, looking to the sample unprocessed_raw.cpp in the original distribution it should be something like:

RawProcessor.open_file(av[i])) 
RawProcessor.unpack())
RawProcessor.imgdata.rawdata.raw_image

So assume it could be the function  function libraw_raw2image

puzzling 

Han

**Comment by laheller** [comment]
> Okay, looking to the sample unprocessed_raw.cpp in the original distribution it should be something like:
> 
> RawProcessor.open_file(av[i]))
> RawProcessor.unpack())
> RawProcessor.imgdata.rawdata.raw_image
> 
> So assume it could be the function function libraw_raw2image
> 
> puzzling
> 
> Han

The only problem is that the final _libraw.dll_ doesn't export any function method providing access to the raw data **after** unpack and **before** process. The _libraw_dcraw_make_mem_image_ method provides us only the processed data. We can call from FreePascal only the exported methods.

**Comment by han-k59** [comment]
How is then unprocessed_raw.exe working?  It requires libraw.dll to function. 

The function raw2mem makes a kind of semi raw image with a pattern red, green, blue, black in colour. But a real raw is monochrome. 

Reading the memory after unpack also doesn't seem to work. img^.data contains only zeros 

The documentation of Libraw is also confusing.

For the moment I give up.

**Comment by han-k59** [comment]
If you can make the missing libraw_data_t structure accessible in the wrapper and the unprocessed raw image can be read, I will provide a raw2fits.pas sample. :)

**Comment by laheller** [comment]
> If you can make the missing libraw_data_t structure accessible in the wrapper and the unprocessed raw image can be read, I will provide a raw2fits.pas sample. :)

Yes, I now. But it is not so easy because it contains a lot of fields and some of them are another structures.
Easier would be to provide a C API **function** which returns directly the value of _image_ field from _libraw_data_t_ structure, then add it to the wrapper.
